spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: h2

logging:
  config: classpath:logback-${spring.profiles.active}.xml

user:
  feign:
    base-url: https://reqres.in
    connection-timeout-millis: 2000
    read-timeout-millis: 5000
    retry:
      period-millis: 1000
      max-period-millis: 2000
      attempts: 3

springdoc:
  swagger-ui:
    path: /api-doc
    url: /docs/openapi.yaml
  api-docs:
    enabled: false